import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from './components/Contact'
import Header from './components/Header'
import Information from './components/Information'
import Nav from './components/Nav'
import Footer from './components/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Reidanse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='lg:h-screen overflow-hidden'>
    <Nav highlightHome={true} />
     <Header />
    </div>
    <Information />
    <Contact />
    <Footer/>
     
    </div>
  )
}
